### ISSUE TITLE
Ende der Registrierung für die Teilnehmer anzeigen

### ISSUE THREAD

**Issue by crymis** [KordonDev/lager-melder#108]
In der Teilnehmer-Ansicht ein Datum mit Uhrzeit einblenden, wann die Registrierung beendet ist.

Doings: 
* [x] Backend: Schnittstelle für Ende-Datum
* [x] Backend: Speichern klappt nicht
* [ ] Frontend: Anbinden und Anzeigen des Ende-Datums
* [ ] Frontend: Für normale Nutzer: Deaktivieren der CRUD Funktionen auf der Teilnehmer-Liste

**Comment by KordonDev** [comment]
Branch: https://github.com/KordonDev/lager-melder/tree/108/end-of-registration

API: Get "/settings/registration-end"

Response: 
```
{
    "registrationEnd": "2022-04-15T21:59:59Z"
}
```

**Comment by crymis** [comment]
Musste fürs Entwickeln erstmal auf einen eigenen Branch: https://github.com/KordonDev/lager-melder/pull/128
