### ISSUE TITLE
Design Edit/Add Attendee

### ISSUE THREAD

**Issue by KordonDev** [KordonDev/lager-melder#12]
As user, I want to Add, Edit and Delete attendees of my department.

AC:
- [x] Add attendee
- [x] Edit Attendee
- [x] Delete Attendee
- [x] Important data are:
    - FirstName
    - LastName
    - TShirt size (see #5 )
    - Food (see #5 )
    - Date of birth / Age

**Comment by KordonDev** [comment]
Responsive Table like https://github.com/gregnb/mui-datatables

Edit in Table like in this example https://community.devexpress.com/blogs/oliver/archive/2017/10/18/react-data-grid-for-google-material-design.aspx

**Comment by KordonDev** [comment]
![image](https://user-images.githubusercontent.com/5114919/88460225-12ddcd00-ce9b-11ea-89e0-9c5e887a22c9.jpeg). This is my broad idea

**Comment by crymis** [comment]
First sketch:
[Feuerwehr Liste.pdf](https://github.com/KordonDev/lager-melder/files/4977995/Feuerwehr.Liste.pdf)

**Comment by KordonDev** [comment]
![Feuerwehr Liste](https://user-images.githubusercontent.com/5114919/91026946-be458300-e5fb-11ea-90a6-89866b0966e4.jpg)
