### ISSUE TITLE
 Attendee status

### ISSUE THREAD

**Issue by KordonDev** [KordonDev/lager-melder#66]
It needs to be documented when a attendee leaves and joins the event event.
## Backend
- [x] Add flag like active to attendee
- [x] Add global events which change active flag

## Frontend
- [x] Disallow to delete global events
- [x] Show entered and left on attendees
- [x] Show numbers of inside attendees

**Comment by crymis** [comment]
![Screenshot 2022-02-26 at 11 52 51](https://user-images.githubusercontent.com/3726683/155840511-079dbc12-dcc8-45a2-b834-6df726b2f936.png)

Rough screenshot for new design.
Show info in table who is actively on the event. Highlight people who are not there (disable, mark greyed).
