### ISSUE TITLE
Statistik with food and tShirt for each department

### ISSUE THREAD

**Issue by KordonDev** [KordonDev/lager-melder#74]
- [x] Create PDF for tShirts in Backend with table for each department
- [x] Change food to Fleisch, Vegetarisch, Muslimisch, Sonderessen
- [x] For "Sonderessen" as needed Attendee name + Department name + chef of department (name + email)
- [x] Show Link for download of PDF in frontend

**Comment by crymis** [comment]
![Screenshot 2022-02-26 at 11 33 30](https://user-images.githubusercontent.com/3726683/155839980-66841ab4-eee3-4954-a5ac-ce9c3115939b.png)

Add table to Overview.vue after h1.

* Remove container with max-width to have more space for data
* Rename Teilnehmer to "Feuerwehr"

**Comment by KordonDev** [comment]
Table will be created in Backend as PDF
[tshirt.pdf](https://github.com/KordonDev/lager-melder/files/8147464/tshirt.pdf)
